/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver */
#ifndef _Included_org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver
#define _Included_org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver
 * Method:    initNativeDriverWithFactory
 * Signature: (Lorg/letras/ps/rawdata/IPenAdapterFactory;)V
 */
JNIEXPORT void JNICALL Java_org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver_runNativeDriver
  (JNIEnv *, jobject);

/*
 * Class:     org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_letras_ps_rawdata_driver_anoto_adp301_AnotoPenDriver_shutdownNativeDriver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
