/*
 *  SpecificPlatform.h
 *  Project: ADP301-Driver for Letras
 *	
 *	This header file declares the functions that the platform specific
 *	part of a Anoto pen driver has to implement.
 *
 *  Created by Niklas Lochschmidt on 29.07.10.
 */

#ifndef IMPORT_SPECIFIC_PLATFORM_HEADER
#define IMPORT_SPECIFIC_PLATFORM_HEADER

/*
 *	starts the platform specific procedure to register for the discovery
 *	of Anoto ADP-301 HID devices. After the discovery of a new HID device, the
 *	functions in CommonInterface.h must be used to send the events generated by the pen.
 *	This call should not return until shutdownPenDiscoveryAndDisconnectAllPens() is called. 
 *	It is important, that successive calls to the pen specific functions provided in
 *	CommonInterface.h must be done from the thread that entered initPenDiscovery()
 *	because otherwise the handles to the Java environment are corrupted.
 */
void initPenDiscovery();

/*
 *	stops the discovery of new pens and disconnects all currently connected pens.
 *	afterwards the thread that is still in initPenDiscovery() must return eventuelly.
 */
void shutdownPenDiscoveryAndDisconnectAllPens();

#endif